// Generates docs/sources.md from the live source registry, and rewrites
// the generated regions of README.md and .env.example between marker
// comments. Hand-written prose outside those markers is left untouched.
//
// `npm run docs` writes the files. `npm run docs -- --check` recomputes
// the same content and exits 1 if any of the three files would change,
// without writing, so CI can catch a registry change that docs weren't
// regenerated for.
import fs from 'node:fs';
import { CONFIG_FIELDS } from '../src/config.ts';
import '../src/sources/all.ts';
import { type Cluster, listSources, type SourceKind } from '../src/sources/registry.ts';
import { TOOL_COUNT } from '../src/toolCount.ts';
import { VERSION } from '../src/version.ts';

const README_PATH = 'README.md';
const ENV_EXAMPLE_PATH = '.env.example';
const SOURCES_DOC_PATH = 'docs/sources.md';

const SOURCES_START = '<!-- sources:start -->';
const SOURCES_END = '<!-- sources:end -->';
const ENV_START = '# env:start';
const ENV_END = '# env:end';

type Source = ReturnType<typeof listSources>[number];

// ── shared helpers ──────────────────────────────────────────────────────────

// Truncates a source description to a single comment line. Deliberately not
// "first sentence": these descriptions are full of abbreviations (St.,
// U.S., v3.) that a period-space split would cut mid-word.
function oneLineSummary(text: string, maxLen = 160): string {
  const oneLine = text.replace(/\s+/g, ' ').trim();
  return oneLine.length > maxLen ? `${oneLine.slice(0, maxLen - 1).trimEnd()}...` : oneLine;
}

function escapeCell(text: string): string {
  return text.replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');
}

function byCluster(sources: Source[]): Map<Cluster, Source[]> {
  const map = new Map<Cluster, Source[]>();
  for (const s of sources) {
    const list = map.get(s.cluster) ?? [];
    list.push(s);
    map.set(s.cluster, list);
  }
  for (const list of map.values()) list.sort((a, b) => a.name.localeCompare(b.name));
  return map;
}

// ── docs/sources.md ──────────────────────────────────────────────────────────

function buildSourcesDoc(sources: Source[]): string {
  const hiddenCount = sources.filter((s) => s.hidden).length;
  const clusters = byCluster(sources);
  const clusterNames = [...clusters.keys()].sort();

  const lines: string[] = [
    '# Sources',
    '',
    'Generated by `npm run docs` from `src/sources/registry.ts`. Do not edit by hand.',
    '',
    `${sources.length} sources across ${clusterNames.length} clusters (${hiddenCount} hidden pending a key or config not present in this deployment).`,
    '',
  ];

  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`## ${cluster} (${list.length})`, '');
    lines.push(
      '| Name | Kind | Cluster | Freshness | Auth env | Optional env | Verified | Description |',
    );
    lines.push('|---|---|---|---|---|---|---|---|');
    for (const s of list) {
      const name = s.hidden ? `${s.name} *(hidden)*` : s.name;
      const authEnv = s.auth?.env ?? 'none';
      const optionalEnv = s.optionalEnv?.length ? s.optionalEnv.join(', ') : '-';
      const verified = s.verifiedAt ?? '-';
      lines.push(
        `| ${name} | ${s.kind} | ${s.cluster} | ${s.freshness} | ${authEnv} | ${optionalEnv} | ${verified} | ${escapeCell(s.description)} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Totals', '');
  lines.push('| Cluster | Sources | Hidden |');
  lines.push('|---|---|---|');
  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`| ${cluster} | ${list.length} | ${list.filter((s) => s.hidden).length} |`);
  }
  lines.push(`| **Total** | ${sources.length} | ${hiddenCount} |`);
  lines.push('');

  return lines.join('\n');
}

// ── README.md ─────────────────────────────────────────────────────────────

function buildReadmeSourcesBlock(sources: Source[]): string {
  const clusters = byCluster(sources);
  const clusterNames = [...clusters.keys()].sort();
  const hiddenCount = sources.filter((s) => s.hidden).length;

  const lines: string[] = [
    SOURCES_START,
    `## Sources (${sources.length})`,
    '',
    `${sources.length} sources across ${clusterNames.length} clusters (${hiddenCount} hidden pending a key or config not present in this deployment). Full per-source detail, including auth env vars and last-verified dates, is generated in [docs/sources.md](docs/sources.md).`,
    '',
    '| Cluster | Sources | Hidden |',
    '|---|---|---|',
  ];
  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`| ${cluster} | ${list.length} | ${list.filter((s) => s.hidden).length} |`);
  }
  lines.push(`| **Total** | ${sources.length} | ${hiddenCount} |`);
  lines.push('', SOURCES_END);

  return lines.join('\n');
}

function buildHealthExample(sources: Source[], toolCount: number): string {
  const hidden = sources.filter((s) => s.hidden).length;
  const byKind: Record<SourceKind, number> = { rest: 0, hub: 0, rss: 0, mcp: 0, scrape: 0 };
  for (const s of sources) byKind[s.kind]++;
  const kindStr = `{ rest: ${byKind.rest}, hub: ${byKind.hub}, rss: ${byKind.rss}, mcp: ${byKind.mcp}, scrape: ${byKind.scrape} }`;
  // quota/cache/calls/errors are runtime counters (Task 4's StateStore,
  // Task 5's per-source metrics); the doc example shows a freshly-started
  // process (nothing reserved, cached, or called yet) rather than today's
  // actual date, so this line does not drift day to day.
  const sourcesStr = `{ total: ${sources.length}, visible: ${sources.length - hidden}, hidden: ${hidden}, calls: 0, errors: 0 }`;
  // backend (final wave, B4): 'state' unless ALEXANDRIA_LEDGER=supabase is
  // configured, same condition createLedger() itself gates on.
  const quotaStr = '{ day: "2026-09-02", reserved: 0, sources: 0, backend: "state" }';
  const cacheStr = '{ entries: 0 }';
  // toolCount is a caller-supplied parameter, not a literal here (task 2
  // review finding): src/index.ts's TOOL_COUNT and this doc example used to
  // carry two separate literals that silently drifted apart when a tool
  // was added. Both now read src/toolCount.ts.
  return `{ status: "ok", version: "${VERSION}", sources: ${sourcesStr}, byKind: ${kindStr}, quota: ${quotaStr}, cache: ${cacheStr}, tools: ${toolCount} }`;
}

function applyReadmeSubstitutions(content: string, sources: Source[]): string {
  let out = content;
  out = out.replace(
    /from \d+ public digital libraries/,
    `from ${sources.length} public digital libraries`,
  );
  out = out.replace(
    /List all \d+ sources with descriptions and full-text capabilities/,
    `List all ${sources.length} sources with descriptions and full-text capabilities`,
  );
  out = out.replace(
    /Health check: `GET \/health` returns `\{[^`]*\}`\./,
    `Health check: \`GET /health\` returns \`${buildHealthExample(sources, TOOL_COUNT)}\`.`,
  );
  return out;
}

// ── .env.example ─────────────────────────────────────────────────────────────

interface EnvVar {
  name: string;
  comment: string;
}

// Feature envs not tied to a single source's `auth` field: transport,
// per-role provider overrides, caching, the web tier, MCP delegation, and
// Supabase storage. Task 5 (review 3.6) moved this list from a
// hand-maintained array to src/config.ts's zod schema - each field's
// `.describe()` text is this section's comment, so the schema is now the
// only place that needs updating when an ops env var is added, renamed, or
// documented. A name that also happens to be a source's declared auth.env
// (JINA_API_KEY) is still listed here only, with the gated source named in
// the registry's own "Source-specific keys" entry for it instead of twice -
// see buildEnvBlock()'s `FEATURE_ENV_NAMES.has(env)` skip below.
//
// UNDECLARED_SOURCE_ENVS covers the opposite edge: an env var an adapter
// reads directly but never declares via `auth`/`optionalEnv` (so the
// registry has no record of it) and that isn't ops-level config either.
// TROVE_FULLTEXT_CAP is the one remaining case (src/sources/trove.ts, out
// of scope for this task per the brief). Kept tiny and explicit rather than
// silently dropping it from .env.example.
const UNDECLARED_SOURCE_ENVS: EnvVar[] = [
  {
    name: 'TROVE_FULLTEXT_CAP',
    comment: 'Max trove full-text reads per run before falling back to metadata. Default 25.',
  },
];

const FEATURE_ENVS: EnvVar[] = [
  ...CONFIG_FIELDS.map(({ name, description }) => ({ name, comment: description })),
  ...UNDECLARED_SOURCE_ENVS,
];

const FEATURE_ENV_NAMES = new Set(FEATURE_ENVS.map((e) => e.name));

function buildEnvBlock(sources: Source[]): string {
  const authVars = new Map<string, string[]>(); // env name -> source names
  for (const s of sources) {
    const env = s.auth?.env;
    if (!env || FEATURE_ENV_NAMES.has(env)) continue;
    const list = authVars.get(env) ?? [];
    list.push(s.name);
    authVars.set(env, list);
  }
  const descByEnv = new Map<string, string>();
  for (const s of sources) {
    const env = s.auth?.env;
    if (env && !descByEnv.has(env)) descByEnv.set(env, s.description);
  }

  const lines: string[] = [
    ENV_START,
    '# Generated by `npm run docs`. Do not edit by hand between these markers.',
    '#',
    '# ── Source-specific keys ────────────────────────────────────────────────',
    '# Each var below is read by src/sources/*.ts and gates one or more sources',
    "# via the registry's `auth` field. A source without a key listed here works",
    '# without any credentials.',
    '',
  ];
  // A required key is often ALSO read optionally by other sources
  // (GITHUB_TOKEN gates githubsearch/githubmcp but merely lifts ghsa's
  // pacing and openiti's search path). Name those too, so the entry does
  // not read as if only the gated sources touch it.
  const optionalUsers = new Map<string, string[]>(); // env name -> source names
  for (const s of sources) {
    for (const env of s.optionalEnv ?? []) {
      const list = optionalUsers.get(env) ?? [];
      list.push(s.name);
      optionalUsers.set(env, list);
    }
  }

  for (const env of [...authVars.keys()].sort()) {
    const usedBy = (authVars.get(env) ?? []).sort().join(', ');
    const desc = descByEnv.get(env) ?? '';
    lines.push(`# ${usedBy}: ${oneLineSummary(desc)}`);
    const alsoOptional = (optionalUsers.get(env) ?? []).sort();
    if (alsoOptional.length > 0) {
      lines.push(`# Also read, but not required, by: ${alsoOptional.join(', ')}.`);
    }
    lines.push(`${env}=`);
    lines.push('');
  }

  // Optional source keys: read by a source but never required by it. Kept
  // in their own section so a reader can tell at a glance which keys unhide
  // a source and which only raise a quota. A name already covered by the
  // required section or by FEATURE_ENVS is not repeated here.
  const optionalVars = new Map<string, string[]>(); // env name -> source names
  for (const [env, names] of optionalUsers) {
    if (FEATURE_ENV_NAMES.has(env) || authVars.has(env)) continue;
    optionalVars.set(env, names);
  }
  if (optionalVars.size > 0) {
    lines.push('# ── Optional source keys ────────────────────────────────────────────────');
    lines.push('# Read by the sources named below but never required by them: each only');
    lines.push('# raises a quota, lifts a rate limit, or unlocks a better backend. Leaving');
    lines.push('# one unset never hides a source.', '');
    for (const env of [...optionalVars.keys()].sort()) {
      const usedBy = (optionalVars.get(env) ?? []).sort().join(', ');
      lines.push(`# ${usedBy}`);
      lines.push(`${env}=`);
      lines.push('');
    }
  }

  lines.push('# ── Feature envs ────────────────────────────────────────────────────────');
  lines.push('# Routing/synthesis provider roles, caching, the web tier, MCP delegation,');
  lines.push('# and vector storage. Every one is optional: the feature it gates is');
  lines.push('# skipped, not failed, when absent.', '');
  for (const { name, comment } of FEATURE_ENVS) {
    lines.push(`# ${comment}`);
    lines.push(`${name}=`);
    lines.push('');
  }

  // Drop the trailing blank line before the end marker.
  while (lines[lines.length - 1] === '') lines.pop();
  lines.push(ENV_END);

  return lines.join('\n');
}

// ── marker splicing ─────────────────────────────────────────────────────────

function spliceMarked(
  content: string,
  startMarker: string,
  endMarker: string,
  inner: string,
): string {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Could not find both "${startMarker}" and "${endMarker}" markers to splice content into.`,
    );
  }
  return content.slice(0, startIdx) + inner + content.slice(endIdx + endMarker.length);
}

// ── main ─────────────────────────────────────────────────────────────────────

function computeAll(): { sourcesDoc: string; readme: string; envExample: string } {
  const sources = listSources();
  const sourcesDoc = buildSourcesDoc(sources);

  const readmeCurrent = fs.readFileSync(README_PATH, 'utf8');
  const readmeWithSources = spliceMarked(
    readmeCurrent,
    SOURCES_START,
    SOURCES_END,
    buildReadmeSourcesBlock(sources),
  );
  const readme = applyReadmeSubstitutions(readmeWithSources, sources);

  const envCurrent = fs.readFileSync(ENV_EXAMPLE_PATH, 'utf8');
  const envExample = spliceMarked(envCurrent, ENV_START, ENV_END, buildEnvBlock(sources));

  return { sourcesDoc, readme, envExample };
}

function main(): void {
  const check = process.argv.includes('--check');
  const { sourcesDoc, readme, envExample } = computeAll();

  if (check) {
    const diffs: string[] = [];
    if (
      !fs.existsSync(SOURCES_DOC_PATH) ||
      fs.readFileSync(SOURCES_DOC_PATH, 'utf8') !== sourcesDoc
    )
      diffs.push(SOURCES_DOC_PATH);
    if (fs.readFileSync(README_PATH, 'utf8') !== readme) diffs.push(README_PATH);
    if (fs.readFileSync(ENV_EXAMPLE_PATH, 'utf8') !== envExample) diffs.push(ENV_EXAMPLE_PATH);
    if (diffs.length) {
      console.error(`docs out of date, run \`npm run docs\`: ${diffs.join(', ')}`);
      process.exit(1);
    }
    console.error('docs up to date');
    return;
  }

  fs.writeFileSync(SOURCES_DOC_PATH, sourcesDoc);
  fs.writeFileSync(README_PATH, readme);
  fs.writeFileSync(ENV_EXAMPLE_PATH, envExample);
  console.error(`wrote ${SOURCES_DOC_PATH}, ${README_PATH}, ${ENV_EXAMPLE_PATH}`);
}

if (process.argv[1]?.endsWith('gen-docs.ts') || process.argv[1]?.endsWith('gen-docs.js')) main();

export {
  buildEnvBlock,
  buildHealthExample,
  buildReadmeSourcesBlock,
  buildSourcesDoc,
  spliceMarked,
};
