// Generates docs/sources.md from the live source registry, and rewrites
// the generated regions of README.md and .env.example between marker
// comments. Hand-written prose outside those markers is left untouched.
//
// `npm run docs` writes the files. `npm run docs -- --check` recomputes
// the same content and exits 1 if any of the three files would change,
// without writing, so CI can catch a registry change that docs weren't
// regenerated for.
import fs from 'node:fs';
import '../src/sources/all.ts';
import { type Cluster, listSources, type SourceKind } from '../src/sources/registry.ts';
import { VERSION } from '../src/version.ts';

const README_PATH = 'README.md';
const ENV_EXAMPLE_PATH = '.env.example';
const SOURCES_DOC_PATH = 'docs/sources.md';

const SOURCES_START = '<!-- sources:start -->';
const SOURCES_END = '<!-- sources:end -->';
const ENV_START = '# env:start';
const ENV_END = '# env:end';

type Source = ReturnType<typeof listSources>[number];

// ── shared helpers ──────────────────────────────────────────────────────────

// Truncates a source description to a single comment line. Deliberately not
// "first sentence": these descriptions are full of abbreviations (St.,
// U.S., v3.) that a period-space split would cut mid-word.
function oneLineSummary(text: string, maxLen = 160): string {
  const oneLine = text.replace(/\s+/g, ' ').trim();
  return oneLine.length > maxLen ? `${oneLine.slice(0, maxLen - 1).trimEnd()}...` : oneLine;
}

function escapeCell(text: string): string {
  return text.replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');
}

function byCluster(sources: Source[]): Map<Cluster, Source[]> {
  const map = new Map<Cluster, Source[]>();
  for (const s of sources) {
    const list = map.get(s.cluster) ?? [];
    list.push(s);
    map.set(s.cluster, list);
  }
  for (const list of map.values()) list.sort((a, b) => a.name.localeCompare(b.name));
  return map;
}

// ── docs/sources.md ──────────────────────────────────────────────────────────

function buildSourcesDoc(sources: Source[]): string {
  const hiddenCount = sources.filter((s) => s.hidden).length;
  const clusters = byCluster(sources);
  const clusterNames = [...clusters.keys()].sort();

  const lines: string[] = [
    '# Sources',
    '',
    'Generated by `npm run docs` from `src/sources/registry.ts`. Do not edit by hand.',
    '',
    `${sources.length} sources across ${clusterNames.length} clusters (${hiddenCount} hidden pending a key or config not present in this deployment).`,
    '',
  ];

  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`## ${cluster} (${list.length})`, '');
    lines.push(
      '| Name | Kind | Cluster | Freshness | Auth env | Optional env | Verified | Description |',
    );
    lines.push('|---|---|---|---|---|---|---|---|');
    for (const s of list) {
      const name = s.hidden ? `${s.name} *(hidden)*` : s.name;
      const authEnv = s.auth?.env ?? 'none';
      const optionalEnv = s.optionalEnv?.length ? s.optionalEnv.join(', ') : '-';
      const verified = s.verifiedAt ?? '-';
      lines.push(
        `| ${name} | ${s.kind} | ${s.cluster} | ${s.freshness} | ${authEnv} | ${optionalEnv} | ${verified} | ${escapeCell(s.description)} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Totals', '');
  lines.push('| Cluster | Sources | Hidden |');
  lines.push('|---|---|---|');
  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`| ${cluster} | ${list.length} | ${list.filter((s) => s.hidden).length} |`);
  }
  lines.push(`| **Total** | ${sources.length} | ${hiddenCount} |`);
  lines.push('');

  return lines.join('\n');
}

// ── README.md ─────────────────────────────────────────────────────────────

function buildReadmeSourcesBlock(sources: Source[]): string {
  const clusters = byCluster(sources);
  const clusterNames = [...clusters.keys()].sort();
  const hiddenCount = sources.filter((s) => s.hidden).length;

  const lines: string[] = [
    SOURCES_START,
    `## Sources (${sources.length})`,
    '',
    `${sources.length} sources across ${clusterNames.length} clusters (${hiddenCount} hidden pending a key or config not present in this deployment). Full per-source detail, including auth env vars and last-verified dates, is generated in [docs/sources.md](docs/sources.md).`,
    '',
    '| Cluster | Sources | Hidden |',
    '|---|---|---|',
  ];
  for (const cluster of clusterNames) {
    const list = clusters.get(cluster) ?? [];
    lines.push(`| ${cluster} | ${list.length} | ${list.filter((s) => s.hidden).length} |`);
  }
  lines.push(`| **Total** | ${sources.length} | ${hiddenCount} |`);
  lines.push('', SOURCES_END);

  return lines.join('\n');
}

function buildHealthExample(sources: Source[]): string {
  const hidden = sources.filter((s) => s.hidden).length;
  const byKind: Record<SourceKind, number> = { rest: 0, hub: 0, rss: 0, mcp: 0, scrape: 0 };
  for (const s of sources) byKind[s.kind]++;
  const kindStr = `{ rest: ${byKind.rest}, hub: ${byKind.hub}, rss: ${byKind.rss}, mcp: ${byKind.mcp}, scrape: ${byKind.scrape} }`;
  // quota/cache are runtime counters (Task 4's StateStore); the doc example
  // shows a freshly-started process (nothing reserved or cached yet) rather
  // than today's actual date, so this line does not drift day to day.
  const quotaStr = '{ day: "2026-09-02", reserved: 0, sources: 0 }';
  const cacheStr = '{ entries: 0 }';
  return `{ status: "ok", version: "${VERSION}", sources: ${sources.length}, visible: ${sources.length - hidden}, hidden: ${hidden}, byKind: ${kindStr}, quota: ${quotaStr}, cache: ${cacheStr}, tools: 9 }`;
}

function applyReadmeSubstitutions(content: string, sources: Source[]): string {
  let out = content;
  out = out.replace(
    /from \d+ public digital libraries/,
    `from ${sources.length} public digital libraries`,
  );
  out = out.replace(
    /List all \d+ sources with descriptions and full-text capabilities/,
    `List all ${sources.length} sources with descriptions and full-text capabilities`,
  );
  out = out.replace(
    /Health check: `GET \/health` returns `\{[^`]*\}`\./,
    `Health check: \`GET /health\` returns \`${buildHealthExample(sources)}\`.`,
  );
  return out;
}

// ── .env.example ─────────────────────────────────────────────────────────────

interface EnvVar {
  name: string;
  comment: string;
}

// Feature envs not tied to a single source's `auth` field: per-role
// provider overrides, caching, the web tier, MCP delegation, and Supabase
// storage. Fixed list and order per the Stage 10 brief. A name that also
// happens to be a source's declared auth.env (CONTACT_EMAIL, JINA_API_KEY,
// TAVILY_API_KEY) is listed here only, with the gated source named in its
// comment, instead of twice.
const FEATURE_ENVS: EnvVar[] = [
  {
    name: 'ALEXANDRIA_BASE_URL',
    comment:
      'Shared OpenAI-compatible gateway base URL for every role (router/synth/research/embeddings/rerank).',
  },
  { name: 'ALEXANDRIA_API_KEY', comment: 'Shared API key paired with ALEXANDRIA_BASE_URL.' },
  {
    name: 'ALEXANDRIA_ROUTER_BASE_URL',
    comment: 'Per-role override: base URL used by library_ask/library_answer routing.',
  },
  { name: 'ALEXANDRIA_ROUTER_API_KEY', comment: 'Per-role override: API key for the router role.' },
  {
    name: 'ALEXANDRIA_ROUTER_MODEL',
    comment: 'Per-role override: chat model used for routing (default gpt-4o-mini).',
  },
  {
    name: 'ALEXANDRIA_SYNTH_BASE_URL',
    comment: 'Per-role override: base URL used by library_answer synthesis.',
  },
  { name: 'ALEXANDRIA_SYNTH_API_KEY', comment: 'Per-role override: API key for the synth role.' },
  {
    name: 'ALEXANDRIA_SYNTH_MODEL',
    comment: 'Per-role override: chat model used for answer synthesis (default gpt-4o-mini).',
  },
  {
    name: 'ALEXANDRIA_RESEARCH_BASE_URL',
    comment: 'Per-role override: base URL used by library_research.',
  },
  {
    name: 'ALEXANDRIA_RESEARCH_API_KEY',
    comment: 'Per-role override: API key for the research role.',
  },
  {
    name: 'ALEXANDRIA_RESEARCH_MODEL',
    comment: 'Per-role override: chat model used for research (default gpt-4o).',
  },
  {
    name: 'ALEXANDRIA_EMBEDDINGS_BASE_URL',
    comment: 'Per-role override: base URL used for library_ingest embeddings.',
  },
  {
    name: 'ALEXANDRIA_EMBEDDINGS_API_KEY',
    comment: 'Per-role override: API key for the embeddings role.',
  },
  {
    name: 'ALEXANDRIA_EMBEDDINGS_MODEL',
    comment: 'Per-role override: embedding model (default text-embedding-3-small).',
  },
  {
    name: 'ALEXANDRIA_RERANK_BASE_URL',
    comment: 'Per-role override: base URL used for the LLM rerank stage.',
  },
  { name: 'ALEXANDRIA_RERANK_API_KEY', comment: 'Per-role override: API key for the rerank role.' },
  {
    name: 'ALEXANDRIA_RERANK_MODEL',
    comment: 'Per-role override: chat model used for rerank (default gpt-4o-mini).',
  },
  {
    name: 'ALEXANDRIA_RERANK',
    comment:
      'Set to "llm" to rerank fused results with a chat call; otherwise the fused order is kept.',
  },
  {
    name: 'ALEXANDRIA_CATALOG_CACHE',
    comment:
      'Path to the routing catalog embedding cache. Defaults to eval/catalog-embeddings.json inside the package.',
  },
  {
    name: 'ALEXANDRIA_CACHE_TTL_MS',
    comment: 'Search result cache TTL in milliseconds. Unset uses the built-in default.',
  },
  {
    name: 'ALEXANDRIA_HTTP_CACHE',
    comment:
      'Path to the shared undici RFC 9111 http-cache SQLite database. Defaults to data/http-cache.db inside the package; falls back to an in-memory cache if that location cannot be created.',
  },
  {
    name: 'ALEXANDRIA_STATE_DB',
    comment:
      'Path to the node:sqlite database backing the daily quota ledger and search result cache. Defaults to data/alexandria.db inside the package; set to ":memory:" to force the in-memory store, or falls back to it automatically if the path can\'t be created.',
  },
  {
    name: 'ALEXANDRIA_LEDGER',
    comment:
      'Set to "supabase" (with SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY) to persist the daily quota ledger there instead of ALEXANDRIA_STATE_DB.',
  },
  {
    name: 'SEARXNG_URL',
    comment: 'Self-hosted SearXNG metasearch instance URL. Hides the searxng source without it.',
  },
  {
    name: 'CRAWL4AI_URL',
    comment:
      'Self-hosted crawl4ai headless-browser render server URL (fetch tier 3). Hides that tier without it.',
  },
  {
    name: 'CRAWL4AI_API_TOKEN',
    comment: 'Bearer token for CRAWL4AI_URL, only needed if your instance requires auth.',
  },
  {
    name: 'JINA_API_KEY',
    comment:
      'Jina AI Reader/Search key. Required to unhide the jinasearch source; also enables fetch tier 2 (jina reader) as a fallback when set.',
  },
  {
    name: 'ALEXANDRIA_JINA_READER',
    comment:
      'Set to 1 to use the jina reader fetch tier anonymously (20 RPM shared cap) when JINA_API_KEY is unset.',
  },
  {
    name: 'TAVILY_API_KEY',
    comment: 'Tavily AI-oriented web search API key. Required to unhide the tavily source.',
  },
  {
    name: 'SUPADATA_API_KEY',
    comment:
      'Supadata transcript service key, preferred for youtube transcripts over the unofficial fallback.',
  },
  {
    name: 'KNOWLEDGE_MCP_URL',
    comment:
      'Optional knowledge-base MCP server URL, folded into library_answer as one more ranked list.',
  },
  { name: 'KNOWLEDGE_MCP_TOKEN', comment: 'Bearer token for KNOWLEDGE_MCP_URL.' },
  {
    name: 'SUPABASE_URL',
    comment:
      'Supabase project URL. Required for library_ingest and for ALEXANDRIA_LEDGER=supabase.',
  },
  {
    name: 'SUPABASE_SERVICE_ROLE_KEY',
    comment:
      'Supabase service role key. Required for library_ingest and for ALEXANDRIA_LEDGER=supabase.',
  },
  {
    name: 'SUPABASE_TABLE',
    comment: 'Table name for library_ingest chunks. Default knowledge_chunks.',
  },
  {
    name: 'CONTACT_EMAIL',
    comment:
      'Courtesy contact email sent to OpenAlex, Crossref, BASE, and similar polite pools; required to unhide the ecosystems source.',
  },
  {
    name: 'TROVE_FULLTEXT_CAP',
    comment: 'Max trove full-text reads per run before falling back to metadata. Default 25.',
  },
  {
    name: 'ALEXANDRIA_ALLOW_LOOPBACK',
    comment:
      'Test-only: lets the fetch tier SSRF guard reach 127.0.0.1/localhost. Never set in production.',
  },
];

const FEATURE_ENV_NAMES = new Set(FEATURE_ENVS.map((e) => e.name));

function buildEnvBlock(sources: Source[]): string {
  const authVars = new Map<string, string[]>(); // env name -> source names
  for (const s of sources) {
    const env = s.auth?.env;
    if (!env || FEATURE_ENV_NAMES.has(env)) continue;
    const list = authVars.get(env) ?? [];
    list.push(s.name);
    authVars.set(env, list);
  }
  const descByEnv = new Map<string, string>();
  for (const s of sources) {
    const env = s.auth?.env;
    if (env && !descByEnv.has(env)) descByEnv.set(env, s.description);
  }

  const lines: string[] = [
    ENV_START,
    '# Generated by `npm run docs`. Do not edit by hand between these markers.',
    '#',
    '# ── Source-specific keys ────────────────────────────────────────────────',
    '# Each var below is read by src/sources/*.ts and gates one or more sources',
    "# via the registry's `auth` field. A source without a key listed here works",
    '# without any credentials.',
    '',
  ];
  // A required key is often ALSO read optionally by other sources
  // (GITHUB_TOKEN gates githubsearch/githubmcp but merely lifts ghsa's
  // pacing and openiti's search path). Name those too, so the entry does
  // not read as if only the gated sources touch it.
  const optionalUsers = new Map<string, string[]>(); // env name -> source names
  for (const s of sources) {
    for (const env of s.optionalEnv ?? []) {
      const list = optionalUsers.get(env) ?? [];
      list.push(s.name);
      optionalUsers.set(env, list);
    }
  }

  for (const env of [...authVars.keys()].sort()) {
    const usedBy = (authVars.get(env) ?? []).sort().join(', ');
    const desc = descByEnv.get(env) ?? '';
    lines.push(`# ${usedBy}: ${oneLineSummary(desc)}`);
    const alsoOptional = (optionalUsers.get(env) ?? []).sort();
    if (alsoOptional.length > 0) {
      lines.push(`# Also read, but not required, by: ${alsoOptional.join(', ')}.`);
    }
    lines.push(`${env}=`);
    lines.push('');
  }

  // Optional source keys: read by a source but never required by it. Kept
  // in their own section so a reader can tell at a glance which keys unhide
  // a source and which only raise a quota. A name already covered by the
  // required section or by FEATURE_ENVS is not repeated here.
  const optionalVars = new Map<string, string[]>(); // env name -> source names
  for (const [env, names] of optionalUsers) {
    if (FEATURE_ENV_NAMES.has(env) || authVars.has(env)) continue;
    optionalVars.set(env, names);
  }
  if (optionalVars.size > 0) {
    lines.push('# ── Optional source keys ────────────────────────────────────────────────');
    lines.push('# Read by the sources named below but never required by them: each only');
    lines.push('# raises a quota, lifts a rate limit, or unlocks a better backend. Leaving');
    lines.push('# one unset never hides a source.', '');
    for (const env of [...optionalVars.keys()].sort()) {
      const usedBy = (optionalVars.get(env) ?? []).sort().join(', ');
      lines.push(`# ${usedBy}`);
      lines.push(`${env}=`);
      lines.push('');
    }
  }

  lines.push('# ── Feature envs ────────────────────────────────────────────────────────');
  lines.push('# Routing/synthesis provider roles, caching, the web tier, MCP delegation,');
  lines.push('# and vector storage. Every one is optional: the feature it gates is');
  lines.push('# skipped, not failed, when absent.', '');
  for (const { name, comment } of FEATURE_ENVS) {
    lines.push(`# ${comment}`);
    lines.push(`${name}=`);
    lines.push('');
  }

  // Drop the trailing blank line before the end marker.
  while (lines[lines.length - 1] === '') lines.pop();
  lines.push(ENV_END);

  return lines.join('\n');
}

// ── marker splicing ─────────────────────────────────────────────────────────

function spliceMarked(
  content: string,
  startMarker: string,
  endMarker: string,
  inner: string,
): string {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Could not find both "${startMarker}" and "${endMarker}" markers to splice content into.`,
    );
  }
  return content.slice(0, startIdx) + inner + content.slice(endIdx + endMarker.length);
}

// ── main ─────────────────────────────────────────────────────────────────────

function computeAll(): { sourcesDoc: string; readme: string; envExample: string } {
  const sources = listSources();
  const sourcesDoc = buildSourcesDoc(sources);

  const readmeCurrent = fs.readFileSync(README_PATH, 'utf8');
  const readmeWithSources = spliceMarked(
    readmeCurrent,
    SOURCES_START,
    SOURCES_END,
    buildReadmeSourcesBlock(sources),
  );
  const readme = applyReadmeSubstitutions(readmeWithSources, sources);

  const envCurrent = fs.readFileSync(ENV_EXAMPLE_PATH, 'utf8');
  const envExample = spliceMarked(envCurrent, ENV_START, ENV_END, buildEnvBlock(sources));

  return { sourcesDoc, readme, envExample };
}

function main(): void {
  const check = process.argv.includes('--check');
  const { sourcesDoc, readme, envExample } = computeAll();

  if (check) {
    const diffs: string[] = [];
    if (
      !fs.existsSync(SOURCES_DOC_PATH) ||
      fs.readFileSync(SOURCES_DOC_PATH, 'utf8') !== sourcesDoc
    )
      diffs.push(SOURCES_DOC_PATH);
    if (fs.readFileSync(README_PATH, 'utf8') !== readme) diffs.push(README_PATH);
    if (fs.readFileSync(ENV_EXAMPLE_PATH, 'utf8') !== envExample) diffs.push(ENV_EXAMPLE_PATH);
    if (diffs.length) {
      console.error(`docs out of date, run \`npm run docs\`: ${diffs.join(', ')}`);
      process.exit(1);
    }
    console.error('docs up to date');
    return;
  }

  fs.writeFileSync(SOURCES_DOC_PATH, sourcesDoc);
  fs.writeFileSync(README_PATH, readme);
  fs.writeFileSync(ENV_EXAMPLE_PATH, envExample);
  console.error(`wrote ${SOURCES_DOC_PATH}, ${README_PATH}, ${ENV_EXAMPLE_PATH}`);
}

if (process.argv[1]?.endsWith('gen-docs.ts') || process.argv[1]?.endsWith('gen-docs.js')) main();

export {
  buildEnvBlock,
  buildHealthExample,
  buildReadmeSourcesBlock,
  buildSourcesDoc,
  spliceMarked,
};
