// One-time generator for src/utils/data/common-english-words.ts, the
// 5,000-word lexicon text-clean.ts's ocrQualityScore() checks Latin-script
// tokens against (task 11, brief 07: "a lexicon-hit ratio ... a bundled
// 5,000-word English list").
//
// Source: word-frequency counts over eight public-domain Project Gutenberg
// texts (fiction, science, and a writing-style guide, to spread coverage
// across everyday, narrative, and expository vocabulary rather than one
// genre): Pride and Prejudice (#1342), The Adventures of Sherlock Holmes
// (#1661), Adventures of Huckleberry Finn (#76), Moby-Dick (#2701), The
// Origin of Species (#1228), The Elements of Style (#37134), Frankenstein
// (#84), The Time Machine (#35). Every one of these is in the US public
// domain (pre-1929 publication); the Gutenberg boilerplate header/footer
// is stripped with the same stripGutenbergWrapper() the ingest pipeline uses,
// so it never enters the word count.
//
// Run once with `node scripts/gen-word-list.ts` and commit the resulting
// file; nothing else re-runs this script (deliberately not part of the
// test suite - it fetches over the network, and the point of committing
// the output is that ocrQualityScore() never needs to).
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { stripGutenbergWrapper } from '../src/utils/text-clean.ts';

const BOOK_IDS = [1342, 1661, 76, 2701, 1228, 37134, 84, 35];
const WORD_LIST_SIZE = 5000;
const OUT_PATH = path.join(import.meta.dirname, '../src/utils/data/common-english-words.ts');

async function fetchBook(id: number): Promise<string> {
  const url = `https://www.gutenberg.org/cache/epub/${id}/pg${id}.txt`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url} failed: ${res.status}`);
  return stripGutenbergWrapper(await res.text());
}

function countWords(text: string, counts: Map<string, number>): void {
  const matches = text.toLowerCase().match(/[a-z]+/g) ?? [];
  for (const word of matches) {
    counts.set(word, (counts.get(word) ?? 0) + 1);
  }
}

async function main(): Promise<void> {
  const counts = new Map<string, number>();
  for (const id of BOOK_IDS) {
    console.log(`fetching Gutenberg #${id}...`);
    countWords(await fetchBook(id), counts);
  }

  const ranked = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  const top = ranked.slice(0, WORD_LIST_SIZE).map(([word]) => word);
  top.sort();

  // Comma-joined into one string (~40KB) rather than a 5,000-entry array
  // literal (~60KB of quotes, brackets and newlines for the same words) -
  // words.split(',') at import time gets the same readonly string[] the
  // caller wants for a fraction of the committed bytes.
  const contents = `// Generated by scripts/gen-word-list.ts - do not hand-edit.
//
// The ${WORD_LIST_SIZE} most frequent words across eight public-domain
// Project Gutenberg texts (see that script's header for the list and
// rationale). Used by src/utils/text-clean.ts's ocrQualityScore() as the
// lexicon a Latin-script chunk's word tokens are checked against.
const COMMON_ENGLISH_WORDS_CSV =
  '${top.join(',')}';

export const COMMON_ENGLISH_WORDS: readonly string[] = COMMON_ENGLISH_WORDS_CSV.split(',');
`;
  writeFileSync(OUT_PATH, contents);
  console.log(`wrote ${top.length} words to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
